# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosbuildsystem' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'vermasdk', :git => 'https://github.com/vermamukesh67/iosbuildsystem.git'

  # Pods for iosbuildsystem

  target 'iosbuildsystemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosbuildsystemUITests' do
    # Pods for testing
  end

end
