# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/vermamukesh67/iosbuildsystem.git'
target 'iosbuildsystem' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'vermasdk'

  # Pods for iosbuildsystem

  target 'iosbuildsystemTests' do
    inherit! :search_paths
pod 'vermasdk'
  end

end
